Found this on Linux macOS with Python and meinheld version Way to reproduce this apy import flask app flaskFlaskname approute def x return x Starting with gunicorn b kmeinheldgmeinheldMeinheldWorker aapp And run wrk wrk c t You can see meinheld worker is exit randomly with logs like this stack smashing detected data homexxxooovenvbinpython terminated Backtrace libx linuxgnulibcso x bfb x fe cbdabfb libx linuxgnulibcso fortifyfail x x fe cc libx linuxgnulibcso fortifyfail x x fe cc data homexxxooovenvlibpython sitepackagesmeinheldservercpython mx linuxgnuso xfe f x fe aaa e f data homexxxooovenvlibpython sitepackagesmeinheldservercpython mx linuxgnusopicoevpollonceinternal x x fe aaae data homexxxooovenvlibpython sitepackagesmeinheldservercpython mx linuxgnuso x f a x fe aaaaf a data homexxxooovenvbinpython PyCFunctionCall x x ffb e data homexxxooovenvbinpython PyEvalEvalFrameEx x ef x ffb dead f data homexxxooovenvbinpython PyEvalEvalFrameEx x b x ffb deaf data homexxxooovenvbinpython x f x ffb df f This only happend with client wrk a HTTP benchmark tool but gunicorn with default worker sync or gevent meinheld with chrome curl have no issue This error appears in the Docker with Django DRF application python Traceback most recent call last File usrlocallibpython sitepackagesmeinheldmloggingpy line in access h environgetREMOTEADDR SystemError method get of dict objects returned a result with an error set When loading the following MDN page got the headers that you can see on the attached image Maybe you guys could cite MDN on your Who uses Meinheld screenshot The Meinheld Gunicorn worker does not appear to call the logaccess method of the Statsd logger correctly when statsdhost is enabled This results in no request stats to be emitted Currently meinheld maintenance is inactive and maintenance cost is very high Major maintenance cost comes from async features eg spawn msocket patch For example Travis fails recently while testlogger I think most meinheld users just want stable and high performance WSGI server And there is asyncio and aiohttp for async requirements How about remove all async features and keep meinheld simple and stable python meinheld POC python usrbinenv python coding utf from meinheld import patch patchpatchall from logginghandlers import SysLogHandler SysLogHandleraddress Result text Traceback most recent call last File testpy line in module SysLogHandleraddress File optpython libpython logginghandlerspy line in init selfsocket socketsocketsocketAFINET socktype File optpython libpython sitepackagesmeinheldmsocketpy line in init selfsetsockoptIPPROTOTCP TCPNODELAY File string line in setsockopt socketerror Errno Protocol not available IPPROTOTCP TCPNODELAY is not imported My Python app core dumped yesterday on a Raspberry Pi running Arch Arm Versions and coredump details are below pi uname a Linux pi ARCH SMP Fri Aug UTC armv l GNULinux pi python version Python pi Datasrcpialarmenvbinpip list formatlegacy Beaker bottle bottlecork greenlet meinheld pifaceio pip pycrypto ruamelyaml setuptools pi coredumpctl gdb PID pialarm UID pi GID pi Signal SEGV Timestamp Fri AEST h ago Command Line envbinpython u homepiDatasrcpialarmpialarm Executable usrbinpython Control Group systemslicepialarmservice Unit pialarmservice Slice systemslice Boot ID c da d d f d fe c d Machine ID d d f ea a b fce Hostname pi Storage varlibsystemdcoredumpcorepialarm c da d d f d fe c d lz Message Process pialarm of user dumped core Stack trace of thread x d na homepiDatasrcpialarmenvlibpython sitepackagesmeinheldservercpython marmlinuxgnueabihfso GNU gdb GDB Copyright C Free Software Foundation Inc License GPLv GNU GPL version or later This is free software you are free to change and redistribute it There is NO WARRANTY to the extent permitted by law Type show copying and show warranty for details This GDB was configured as armv lunknownlinuxgnueabihf Type show configuration for configuration details For bug reporting instructions please see Find the GDB manual and other documentation resources online at For help type help Type apropos word to search for commands related to word Reading symbols from usrbinpython no debugging symbols founddone warning core file may not match specified executable file New LWP New LWP New LWP Thread debugging using libthreaddb enabled Using host libthreaddb library usrliblibthreaddbso Core was generated by envbinpython u homepiDatasrcpialarmpialarm Program terminated with signal SIGSEGV Segmentation fault importgreenlet at meinheldservergreensupportc meinheldservergreensupportc No such file or directory Current thread is Thread x f d LWP gdb where importgreenlet at meinheldservergreensupportc greenletnew o x d d parent x at meinheldservergreensupportc x c in callwsgihandler clientoptimized out at meinheldserverserverc x b c in acceptcallback loop x bf fd eventsoptimized out cbargoptimized out at meinheldserverserverc x b in picoevpollonceinternal looploopentry x bf maxwaitoptimized out at meinheldserverpicoevepollc x c in picoevlooponce maxwaitoptimized out loop x bf at meinheldserverpicoevh meinheldrunloop selfoptimized out argsoptimized out kwdsoptimized out at meinheldserverserverc x cbdb in PyCFunctionFastCallDict from usrliblibpython mso x d e in from usrliblibpython mso Backtrace stopped previous frame identical to this frame corrupt stack gdb Occurred after updating system and rebooting but unfortunately I can not repeat the crash so seems just a oneoff atm I am raising this issue so it is known about This app has been running for many years although I frequently update system and PyPI packages though Hello I have noticed an error when i use dnspython in django app using meinheld backend of circus My app use python My django app is lauching DNS request to check some parameters provided by users if DNS is not correctly configured an error is shown to users The following launch DNS request python resolver dnsresolverResolver resolvernameservers selfgetdnshost resolvertimeout resolverlifetime try answers resolverqueryselfsdaenumformat NAPTR except dnsexceptionTimeout as e raise PdnsDnsErrorstre except dnsresolverNXDOMAIN as e raise PdnsDnsErrorstre Then i run my app using this command bash chaussette backend meinheld voxisdaswsgiapplication port host And a dnsexceptionTimeout is raised Do you have any clue about this error No DNS request is sent to my DNS server If i run my app with waitress for example no error is raised All queries are OK Thanks in advance Hello I have an application that I recently switched from gunicorngevent workers to gunicornmeinheld and it is now having memory leak issues The issues disappear when I switch back to gevent I havent done much investigation at the moment because I am busy with work but I plan on doing it later this week Is there anything in particular I should look for to see if this is really related to meinheld I am using the following meinheldrelated packages in the application greenlet gunicorn meinheld and the following gunicorn config bind workers if currentenv DEV else multiprocessingcpucount workerclass eggmeinheldgunicornworker procname api accesslogformat hs ls us ts rs ss bs fs as XRealIPis Ls accesslog errorlog The application is basically a more complex version of this Thank you 